### ISSUE TITLE
Tag a stable version

### ISSUE THREAD

**Issue by maks-rafalko** [bematech/libmpdec#2]
Would you mind creating a tag or github release?

What I want to achieve: `git clone --branch 1.0.0 --depth 1 https://github.com/bematech/libmpdec.git`

Currently I need to clone master and checkout to particular commit, when image for docker is being build.

Thank you.

**Comment by maks-rafalko** [comment]
ping @marcelo-rocha

**Comment by skrah** [comment]
This appears to be an obsolete copy of `libmpdec`, which nevertheless occupies the top Google result.

The actual upstream is:

https://www.bytereef.org/mpdecimal/index.html
https://www.bytereef.org/mpdecimal/download.html

The latest stable release is:

https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-2.5.1.tar.gz

**Comment by paulocmoreno** [comment]
@skrah and @maks-rafalko, this fork was for internal use and is no longer needed. We will remove it to avoid promoting the obsolete version. Thanks for reporting the issue.
